#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2012 OpenWrt.org
#
# NFCAPD init script tweaked for LogWRT
# Key changes:
#  * Run as user nfdump
#  * Use dynamic subdir per source
#  * Check for storage availability
#  * Create dir if needed

START=60
USE_PROCD=1
pidfile=/var/run/nfcapd/nfcapd.pid
nfuser=nfdump
nfmount=/mnt/logstore/
nfdirectory=/mnt/logstore/flowdata
PROG=/usr/bin/nfcapd

validate_nfcapd_section() {
        uci_validate_section nfcapd nfcapd "${1}" \
                'enabled:bool' \
                'port:string'
}
validate_nfexpire_section() {
        uci_validate_section nfcapd nfexpire "${1}" \
                'max_space:string' \
                'max_age:string'
}

start_service() {
        validate_nfcapd_section nfcapd || {
                echo "nfcapd configuration validation failed"
                return 1
        }
        validate_nfexpire_section nfexpire || {
                # NB: "validate" doesn't actuall check these options exist!
                echo "nfexpire configuration validation failed"
                return 1
        }

        findmnt "$nfmount" > /dev/null || {
                echo "external storage not mounted"
                return 100
        }

        [ "$enabled" -gt 0 ] && {
                # nfdump writes pidfil as non-root with -u so give it a directory to use
                mkdir -p /var/run/nfcapd
                chown nfdump:nfdump /var/run/nfcapd
                # Check and create storage directory
                mkdir -p "$nfdirectory"
                chown $nfuser:$nfuser "$nfdirectory"

                # Use nfexpire to set autoexpiry settings
                su $nfuser -s /bin/ash -c "/usr/bin/nfexpire -u $nfdirectory -s $max_space -t $max_age "

                procd_open_instance
                procd_set_param stdout 1
                procd_set_param stderr 1
                procd_set_param command "$PROG"
                procd_append_param command -S 1 -P "$pidfile" -p "$port" -M "$nfdirectory" -w -e -u $nfuser -g $nfuser
                procd_close_instance
        }
}
